title: "I leverage synergies."
highlighter: pygments
markdown: kramdown
pygments: true
permalink: /:year/:title/
copyright_year: 2011
paginate: 10
analyticscode: UA-3288725-2
encoding: utf-8
exclude: [package.json, Makefile, Gruntfile.js, node_modules]
