title: "I leverage synergies."
highlighter: pygments
markdown: redcarpet
highlighter: pygments
permalink: /:year/:title/
copyright_year: 2015
paginate: 10
analyticscode: UA-3288725-2
encoding: utf-8
exclude: [package.json, Makefile, Gruntfile.js, node_modules]
gems:
    - jekyll-redirect-from
